eckinox_admin_ui:
    menus:
        multilevel:
            sidebar:
                dashboard:
                    children:
                        application:
                            label: Sites / Applications
                            icon: star
                            children:
                                list:
                                    label: Liste
                                    route_name: website_list
                                create:
                                    label: Nouveau
                                    route_name: website_create
