eckinox_admin_ui:
    menus:
        multilevel:
            sidebar:
                dashboard:
                    children:
                        list:
                            label: Sites / Applications
                            icon: star
                            route_name: website_list
                        category:
                            label: Catégories
                            icon: list
                            route_name: category_list
