symfonycasts_reset_password:
    request_password_repository: Eckinox\SecurityBundle\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 60
    enable_garbage_collection: true